name: nginx-deployment
on: push
jobs:
  my-job:
    runs-on: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checking Docker Images
        shell: cmd
        run: docker images
    
   
 
 
